export const modelNames = [
  "interviewLogistics",
  "question",
  "interviewImpression",
  "lOIResponse",
  "postIVCommunication",
  "secondLook",
  "dropped",
  "fameShame",
  "m4InternImpression",
  "malignant",
  "scheduleDetails",
  "fellowshipMatch",
  "interviewInvite",
  "interviewRejection",
  "cityUserInput",
  "xorY",
];
